# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 15:18
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCaixa', models.CharField(max_length=6, unique=True, verbose_name='Id Caixa')),
                ('autorizacao', models.CharField(max_length=20, unique=True, verbose_name='Autorização da Caixa')),
                ('corCaixa', models.CharField(max_length=7, null=True, verbose_name='Cor da Tarja')),
                ('informacaoAdicional', models.TextField(max_length=200, verbose_name='Informações Adicionais')),
                ('createdEm', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registro criado em:')),
                ('createdPor', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detalhe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numLongitudeDeta', models.CharField(max_length=10, verbose_name='Longitude')),
                ('numLatitudeDeta', models.CharField(max_length=10, verbose_name='Latitude')),
                ('numTemperaturaDeta', models.CharField(max_length=10, verbose_name='Temperatura')),
                ('indVirouDeta', models.BooleanField(verbose_name='Virou?')),
                ('indTombouDeta', models.BooleanField(verbose_name='Tombou?')),
            ],
            options={
                'verbose_name': 'Detalhe',
                'verbose_name_plural': 'Detalhes',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEquipamento', models.CharField(max_length=6, unique=True, verbose_name='Id Equipamento')),
                ('imeiEquipamento', models.CharField(max_length=22, unique=True, verbose_name='IMEI do Equipamento')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('operadora', models.CharField(choices=[('Vivo', 'Vivo'), ('Oi', 'Oi'), ('Tim', 'Tim'), ('Claro', 'Claro'), ('Nextel', 'Nextel')], max_length=8, verbose_name='Operadora')),
                ('imeiSimCard', models.CharField(max_length=26, verbose_name='IMEI SIM Card')),
                ('createdEm', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registro criado em:')),
                ('createdPor', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Hospital')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('nomeResponsavel', models.CharField(max_length=30, verbose_name='Responsável')),
                ('emailResponsavel', models.CharField(max_length=50, verbose_name='E-mail')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=50, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=30, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=30, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('createdEm', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registro criado em:')),
                ('createdPor', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hospitais',
            },
        ),
        migrations.CreateModel(
            name='Importa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=22, unique=True, verbose_name='IMEI')),
                ('dia', models.DateField(max_length=10, verbose_name='Dia')),
                ('hora', models.TimeField(max_length=8, verbose_name='Hora')),
                ('longitude', models.IntegerField(verbose_name='Longitude')),
                ('latitude', models.IntegerField(verbose_name='Latitude')),
                ('altitude', models.IntegerField(verbose_name='Altitude')),
                ('velocidade', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Velocidade')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Temperatura')),
                ('vibra', models.BooleanField(verbose_name='Vibrou?')),
                ('tombo', models.BooleanField(verbose_name='Tombou?')),
                ('course', models.IntegerField(verbose_name='Curso')),
                ('satelites', models.SmallIntegerField(verbose_name='Satélites')),
                ('createdEm', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registro criado em:')),
                ('createdPor', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dscStatus', models.CharField(max_length=50)),
                ('codStatus', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTransportador', models.CharField(blank=True, max_length=30, null=True, verbose_name='Transportado por')),
                ('contato', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contato')),
                ('obs', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observações')),
                ('createdEm', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registro criado em:')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Caixa')),
                ('createdPor', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Equipamento')),
                ('localChegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_chegada', to='core.Hospital')),
                ('localPartida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_partida', to='core.Hospital')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='core.Status')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
            },
        ),
        migrations.AddField(
            model_name='detalhe',
            name='viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Viagem'),
        ),
    ]
