# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCaixa', models.CharField(max_length=5, verbose_name='Identifica\xe7\xe3o da Caixa')),
                ('autorizacao', models.CharField(max_length=50, verbose_name='Autoriza\xe7\xe3o da Caixa')),
                ('corCaixa', models.CharField(max_length=7, null=True, verbose_name='Cor da Tarja')),
                ('informacaoAdicional', models.TextField(max_length=100, verbose_name='Informa\xe7\xf5es Adicionais')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=5, verbose_name='Equipamento')),
                ('imeiEquipamento', models.CharField(max_length=22, verbose_name='IMEI do Equipamento')),
                ('telefone', models.CharField(max_length=22, verbose_name='Telefone')),
                ('operadora', models.CharField(choices=[('Vivo', 'Vivo'), ('Oi', 'Oi'), ('Tim', 'Tim'), ('Claro', 'Claro'), ('Nextel', 'Nextel')], max_length=8, verbose_name='Operadora')),
                ('imeiSimCard', models.CharField(max_length=26, verbose_name='IMEI SIM Card')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Hospital')),
                ('telefone', models.CharField(max_length=19, verbose_name='Telefone')),
                ('nomeResponsavel', models.CharField(max_length=30, verbose_name='Respons\xe1vel')),
                ('emailResponsavel', models.CharField(max_length=50, verbose_name='E-mail')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=50, verbose_name='Endere\xe7o')),
                ('bairro', models.CharField(max_length=30, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=30, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name_plural': 'Hospitais',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codStatus', models.CharField(max_length=10)),
                ('dscStatus', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Caixa')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Equipamento')),
                ('localChegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_chegada', to='core.Hospital')),
                ('localPartida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_partida', to='core.Hospital')),
                ('status', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='status', to='core.Status')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
            },
        ),
    ]
