# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='codStatus',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='status',
            name='dscStatus',
            field=models.CharField(max_length=50),
        ),
    ]
