# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171027_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalhe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numLongitudeDeta', models.CharField(max_length=10, verbose_name='Longitude')),
                ('numLatitudeDeta', models.CharField(max_length=10, verbose_name='Latitude')),
                ('numTemperaturaDeta', models.CharField(max_length=10, verbose_name='Temperatura')),
                ('indVirouDeta', models.BooleanField(verbose_name='Virou?')),
                ('indTombouDeta', models.BooleanField(verbose_name='Tombou?')),
            ],
            options={
                'verbose_name': 'Detalhe',
                'verbose_name_plural': 'Detalhes',
            },
        ),
        migrations.AlterField(
            model_name='viagem',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='core.Status'),
        ),
        migrations.AddField(
            model_name='detalhe',
            name='viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Viagem'),
        ),
    ]
