# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171027_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhe',
            name='numLatitudeDeta',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='detalhe',
            name='numLongitudeDeta',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='detalhe',
            name='numTemperaturaDeta',
            field=models.IntegerField(verbose_name='Temperatura'),
        ),
    ]
