# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171102_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhe',
            name='viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='core.Viagem'),
        ),
    ]
