# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171102_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhe',
            name='numTemperaturaDeta',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Temperatura'),
        ),
    ]
