# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 13:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171106_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhe',
            name='datDateDeta',
            field=models.DateField(default=datetime.datetime(2017, 11, 8, 11, 47, 42, 797493), verbose_name='Data'),
        ),
    ]
