# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_viagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name_plural': 'Hospitais'},
        ),
        migrations.AlterModelOptions(
            name='viagem',
            options={'verbose_name_plural': 'Viagens'},
        ),
    ]
