# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171019_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='teste',
            field=models.CharField(default='', max_length=250),
        ),
    ]
