# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_viagem_teste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codStatus', models.CharField(max_length=10)),
                ('dscStatus', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='viagem',
            name='teste',
        ),
        migrations.AddField(
            model_name='viagem',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='status', to='core.Status'),
        ),
    ]
