# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 16:42
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171109_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='createdPor',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
