# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=4)),
                ('imeiEquipamento', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=15)),
                ('operadora', models.CharField(max_length=16)),
                ('imeiSimCard', models.CharField(max_length=22)),
            ],
        ),
    ]
