# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCaixa', models.CharField(max_length=250)),
                ('corCaixa', models.CharField(max_length=250)),
                ('informacaoAdicional', models.TextField()),
            ],
        ),
    ]
