# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_caixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.Caixa'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='cor',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='corCaixa',
            field=models.CharField(max_length=250, verbose_name='Cor da Tarja'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='idCaixa',
            field=models.CharField(max_length=250, verbose_name='Identifica\xe7\xe3o da Caixa'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='informacaoAdicional',
            field=models.TextField(verbose_name='Informa\xe7\xf5es Adicionais'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='imeiEquipamento',
            field=models.CharField(max_length=15, verbose_name='IMEI'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='imeiSimCard',
            field=models.CharField(max_length=22, verbose_name='IMEI SIM Card'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='operadora',
            field=models.CharField(choices=[('Vivo', 'Vivo'), ('Oi', 'Oi'), ('Tim', 'Tim'), ('Claro', 'Claro'), ('Nextel', 'Nextel')], max_length=16),
        ),
    ]
