# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20171011_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='corCaixa',
            field=models.CharField(max_length=7, null=True, verbose_name='Cor da Tarja'),
        ),
    ]
