# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20171011_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('telefone', models.CharField(max_length=16)),
                ('nomeResponsavel', models.CharField(max_length=250, verbose_name='Respons\xe1vel')),
                ('emailResponsavel', models.CharField(max_length=250, verbose_name='E-mail')),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
    ]
