# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Caixa')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Equipamento')),
                ('localChegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_chegada', to='cadastro.Hospital')),
                ('localPartida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_partida', to='cadastro.Hospital')),
            ],
        ),
    ]
